[package]
name = "meow-openconnect"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "AnyConnect authentication and CSTP packet transport for meow-rs."

[dependencies]
tokio = { workspace = true }
tokio-util = { workspace = true }
roxmltree = "0.21.1"

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }

[lints]
workspace = true
